### ISSUE TITLE
The script is not checking if the image is an actual image, just its extension

### ISSUE THREAD

**Issue by moeenio** [Anteste/Image-Hoster#1]

**Comment by moeenio** [comment]
Why closed? Fixed? Irrelevant?

**Comment by Anteste** [comment]
Hi locness3, I closed this issue because this php script was just an exercice that I did when I was a beginer in 2017.
I will look at it but if you can fix it you can submit a pull request

**Comment by moeenio** [comment]
> was just an exercice

Then you should point that out. And probably not host it publicly...

**Comment by Anteste** [comment]
It's my bad
